Maqueta en HTML de la primera entrega
Lucaaaa05/Programacion-Web-LucaE pull request #1
Opened 2024-08-20 21:57 UTC by Lucaaaa05

En este codigo podemos ver la maqueta de la página "Practicasa", utilizando etiquetas basicas de HTML5.
Se puede ver el logo, una sección de indices, un poco de información de la empresa y un formulario para dejar preguntas, en el footer vemos el contacto de la empresa, como donde se encuentra, y varias redes.

2024-08-21 01:41 UTC, MVelasquez98 requested changes
Falta el archivo readme.md. La consigna solicita:
"Antes de iniciar con el desarrollo del proyecto, es fundamental proporcionar una descripción detallada del mismo en el archivo [README.md](https://docs.github.com/es/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes) de tu repositorio en GitHub. Este archivo actúa como la primera impresión del proyecto para cualquier persona que visite el repositorio, por lo que debe ser claro, conciso y completo"

2024-08-21 01:41 UTC, MVelasquez98 commented on Prueba Pagina 1/index.html
> +        <section id="productos">
La actividad solicita:
"Incluye elementos básicos como título, párrafos, imágenes, enlaces, listas, formularios y tablas relacionados con tu tema."
Falta utilizar tablas, que bien podría usarse aca una tabala de productos/precios por ejemplo

2024-08-21 01:46 UTC, MVelasquez98 reviewed
PUNTAJE POR CONSIGNA:
1. Estructura HTML (3 puntos):
   -  Uso correcto de HTML5 para estructurar la página. :heavy_check_mark:
   - Completa inclusión de elementos básicos como título, párrafos, imágenes, enlaces, listas y tablas relacionados con el tema elegido. :x:
    - Introduce etiquetas semánticas pertinentes para mejorar la accesibilidad y el SEO. :heavy_check_mark:
2. GitHub (5 puntos):
    - Correcta creación de ramas "master" y "develop" en el repositorio. :heavy_check_mark:
  - Creación de una rama "feature/primera-entrega" y habilitación de GitHub Pages para esa rama. :heavy_check_mark:
   - Realización de commits necesarios sobre la rama de desarrollo. :heavy_check_mark:
   - Correcta creación de la pull request contra la rama "develop". :heavy_check_mark:
   - Entrega de la URL de la pull request y la URL generada por GitHub Pages. :heavy_check_mark:

3. Documentación (2 puntos):
   - Inclusión de comentarios claros y concisos en el código HTML. :x: 
  - Realizar una descripción y overview del proyecto elegido en el readme.md del repositorio :x: 
  
 Nota: 7 (Siete)

2024-09-10 17:34 UTC, Lucaaaa05 commented
@MVelasquez98 Agregé nuevas tablas para productos, 2 botones nuevos "lo más vendido" y "ofertas", imagenes para productos mejore un poco la maqueta y utilizé Prittier para mejorar el formato, y por ultimo añadí un README.md

2024-09-13 14:56 UTC, merged