Release/segundo parcial
Lucaaaa05/Programacion-Web-LucaE pull request #10
Opened 2024-11-28 16:10 UTC by Lucaaaa05

## Describir cambios realizados

## Checklist:
- [x] Realizé una autoevaluación de mi código.
- [ ] Si es una característica principal, he hecho pruebas exhaustivas.
- [x] ¿Será parte de una actualización del producto? Si es así, por favor escribe una frase sobre esta actualización.
        - **Agregado de API**

### Reglas
![image](https://github.com/user-attachments/assets/8326ed08-30ca-4429-96c3-ee98085194a6)

![image](https://github.com/user-attachments/assets/46093206-9e53-4df5-8ad6-486593ea180b)

![image](https://github.com/user-attachments/assets/2fe98e08-04e3-4d60-b49a-deab5f91b7e3)

2024-11-30 19:33 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA**:
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

- **Asincronía y Manejo de Datos (3 puntos)**
✅ 1 punto: Utiliza AJAX y JSON para obtener datos de forma asíncrona, manejando adecuadamente promises y fetch para consumir alguna API mock .
✅ 1 punto: La información estática esta en formato JSON, se carga y utiliza de manera asíncrona.
✅ 1 punto: Recorrido de colecciones siendo óptimo utilizando funciones de orden superior. No aplica porque no usa AJAX ni JSON

- **Gestión del Proyecto y Buenas Prácticas con GitHub (7 puntos)**:
✅ 1 punto: Realización de commits necesarios sobre la rama de desarrollo utilizando Git.
✅ 1 punto: Creación de una rama release/segundo-parcial a partir de la rama develop utilizando Git.
✅ 1 punto: Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama feature/cuarta-entrega con develop en GitHub.
✅ 1 punto: Proporcionar la URL de la pull request y la URL generada por GitHub Pages para la rama release/segundo-parcial como parte de la entrega.
⚠️ 0.50 puntos: Implementa un archivo [CHANGELOG.md](https://github.com/Laboratoria/changelog-guide) documentando los cambios realizados en el proyecto en cada entrega o versión, siguiendo un formato estructurado. Revisar cambios propuestos, algo más completo. Tomar el comentario solo como modelo, rellenar correctamente.
✅  1 punto: Configura [reglas en GitHub](https://docs.github.com/es/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule) para bloquear push directos a las ramas develop y master, exigiendo pull requests con al menos un revisor aprobado para realizar merges. Incluir en el comentario de la pull request una captura con el estado de las reglas.
⚠️0.50 puntos: No Implementa una [plantilla (template) de pull request](https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) en el repositorio para estandarizar las solicitudes de revisión y asegurarse de incluir in[formación relevante](https://axolo.co/blog/p/part-3-github-pull-request-template) (descripción, cambios realizados, pruebas realizadas, etc.). Puede mejorarse la plantilla, tomar en cuenta las mejoras propuestas. 

**Nota**: 9(Nueve)

**Comentarios**:  ¡Excelente trabajo hasta ahora! Alcanzaste un muy buen nivel en la implementación del proyecto, especialmente en el manejo de datos de manera asíncrona y en la gestión del proyecto con GitHub. Te dejo algunas recomendaciones finales para asegurar un proyecto más sólido para la entrega final:

- Mejorar el CHANGELOG.md: Asegúrate de que esté completo y detallado para todas las entregas. Eso no solo te va ayudar a mantener un registro claro de la evolución del proyecto, sino que también facilitará el proceso de revisión para otros.

- Plantilla de Pull Request: Aunque creaste una plantilla básica, tómate un tiempo para revisarla y asegurar que incluya todos los detalles necesarios como descripciones de cambios, pruebas realizadas y cualquier otro dato relevante que pueda ser útil para los revisores.
Mira este template, solo de ejemplo:
```
<!--- Provide a general summary of your changes in the Title above -->

<!-- Check and try your best to make your commits follow the guidelines explained in https://chris.beams.io/posts/git-commit/ -->

## Description

<!--- Describe your changes in detail -->

## Motivation and Context

<!--- Why is this change required? What problem does it solve? -->
<!--- If it fixes an open issue, please link to the issue here. -->

## Types of changes

<!--- What types of changes does your code introduce? Put an `x` in all the boxes that apply: -->
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

<!--- Go over all the following points, and replace `[ ]` with `[x]` in all the boxes that apply. -->
<!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -->
- [ ] My code follows the [code style](https://github.com/mercadolibre/fury_go-toolkit/blob/master/STYLE.md) of this project.
- [ ] My commits follow as good as possible the guidelines indicated in [How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/).
- [ ] My Pull Request follows the [Contribution and Pull Requests Etiquette](https://github.com/melisource/fury_acq-parameterstore-api/blob/develop/CONTRIBUTE.MD).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly (if applicable).
- [ ] I have updated the CHANGELOG.
- [ ] I have tested in Fury (if apply).
```
Estas mejoras no solo cumplirán con los requisitos de la materia, sino que también te proporcionarán una base más profesional y estructurada para futuros proyectos. ¡Seguí adelante con este gran esfuerzo y exitos con la entrega final!

2024-11-30 19:33 UTC, MVelasquez98 commented on Carrito.js
> +            const respuesta = await fetch("https://fakestoreapi.com/products");
Comprueba si la respuesta del fetch es exitosa con respuesta.ok antes de procesar el JSON. Esto maneja mejor los errores de red o de servidor.
```suggestion
       const respuesta = await fetch("https://fakestoreapi.com/products");
        if (!respuesta.ok) {
            throw new Error('Error al obtener datos de la API');
        }
        const productos = await respuesta.json();
```

2024-11-30 19:33 UTC, MVelasquez98 commented on Carrito.js
> +            const productoHTML = `
En lugar de usar innerHTML +=, es más eficiente crear y añadir directamente nuevos elementos al DOM usando createElement y appendChild.
```suggestion
         const productoDiv = document.createElement('div');
         productoDiv.classList.add('producto', 'card');
         productoDiv.innerHTML = `
```

2024-11-30 19:33 UTC, MVelasquez98 commented on Carrito.js
> +            contenedorProductos.innerHTML += productoHTML;
```suggestion
            contenedorProductos.appendChild(productoDiv);
```

2024-11-30 19:33 UTC, MVelasquez98 commented on Carrito.js
> +            this.productos = this.productos.filter((producto) => producto.nombre !== nombreProducto);
Mantente consistente asignando el resultado del filtro a una nueva variable primero para asegurar que las notificaciones se muestren correctamente antes de modificar this.productos.
`const nuevoListado = this.productos.filter((producto) => producto.nombre !== nombreProducto);`

2024-11-30 19:33 UTC, MVelasquez98 commented on Carrito.js
> +
```suggestion
   this.productos = nuevoListado;
```

2024-11-30 19:33 UTC, MVelasquez98 commented on CHANGELOG.md
> +# Release Segundo Parcial
Te propopongo un registro de cambios más completo y ordenado. Por ejemplo:
```
# Registro de Cambios

## Primer Parcial: Entregas 1 y 2

### Entrega Actividad Obligatoria 1 - [Fecha: 2023-04-20]
- **Clase Carrito:**
  - Implementación inicial de la clase `Carrito`.
  - **Pull Request:** [#1](https://github.com/usuario/repositorio/pull/1)

- **HTML Estructura Base:**
  - Creación de la estructura básica del HTML para la aplicación.
  - **Pull Request:** [#1](https://github.com/usuario/repositorio/pull/1)

### Entrega Actividad Obligatoria 2 - [Fecha: 2023-05-15]
- **Clase Notificaciones:**
  - Implementación inicial de la clase `Notificaciones`.
  - **Pull Request:** [#2](https://github.com/usuario/repositorio/pull/2)

- **Estilos CSS:**
  - Se agregaron estilos básicos a los elementos principales de la aplicación.
  - **Pull Request:** [#2](https://github.com/usuario/repositorio/pull/2)

## Segundo Parcial: Entregas 3 y 4

### Entrega Actividad Obligatoria 3 - [Fecha: 2023-09-10]
1. **Clase Carrito:**
   - Se le dio formato al documento.
   - Se agregaron métodos para la carga de productos de la API [FakeStore API](https://fakestoreapi.com/) y para mostrarlos en el HTML.
   - **Pull Request:** [#3](https://github.com/usuario/repositorio/pull/3)

2. **Clase Notificaciones:**
   - Se le dio formato al documento.
   - **Pull Request:** [#3](https://github.com/usuario/repositorio/pull/3)

### Entrega Actividad Obligatoria 4 - [Fecha: 2023-10-05]
3. **Script.js:**
   - Ahora los botones se inicializan desde el método `cargarProductosAPI`.
   - **Pull Request:** [#4](https://github.com/usuario/repositorio/pull/4)

4. **Styles.css:**
   - Se le dio formato al documento.
   - Cambios de diseño en los productos. **Nota:** Aún faltan mejoras en el diseño.
   - **Pull Request:** [#4](https://github.com/usuario/repositorio/pull/4)
```

2024-12-08 15:09 UTC, Lucaaaa05 commented
@MVelasquez98 
Buenas profe, hice los cambios que sugirió, estan los cambios en el CHANGELOG.
Además hice una nueva [PR template](https://github.com/Lucaaaa05/Programacion-Web-LucaE/pull/11)
Fijesé si esta todo bien, espero su respuesta
Saludos.

2024-12-10 14:13 UTC, MVelasquez98 approved these changes
LGTM

2024-12-10 15:25 UTC, merged