segunda entrega css (diseños)
Lucaaaa05/Programacion-Web-LucaE pull request #2
Opened 2024-09-16 18:49 UTC by Lucaaaa05

Se crearon todos los diseños en css, en el archivo "styles.css", en un futuro se planea implementar favoritos y carrito de compra.

2024-09-25 15:18 UTC, MVelasquez98 requested changes
Revisa las media querys para dispositivos moviles, no esta siendo responsivo en la parte del encabezado:
<img width="355" alt="image" src="https://github.com/user-attachments/assets/6c82072f-311f-4549-9117-eac901254c71">

2024-09-25 15:21 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

**Mejoras en la Maquetación CSS (5 puntos):**
- Implementación eficaz de diferentes tipos de selectores y aprovechamiento de la herencia de estilos para simplificar el código CSS. (1 punto) ✔️
- Aplicación correcta de formatos y fuentes para mejorar la legibilidad y estética del contenido, utilizando las propiedades CSS correspondientes. (1 punto) ✔️
- Uso adecuado de modelos de caja (box model) para controlar el tamaño, margen, relleno y bordes de los elementos de la página. (1 punto) ✔️
- Diferenciación clara entre elementos en línea y elementos en bloque mediante estilos CSS apropiados, demostrando comprensión de las diferencias y su aplicación en el diseño web. (1 punto) ✔️
- Implementación efectiva de columnas utilizando técnicas como elementos flotantes, display: flex y display: grid, según corresponda al diseño requerido. (1 punto) ✔️

**Diseño de Columnas y Layouts Responsive (2 puntos):**
- Correcta utilización de media queries para crear un diseño responsive que se adapte de manera adecuada a diferentes tamaños de pantalla y dispositivos. (1 punto) ✔️
- Estructuración satisfactoria de layouts utilizando contenedores, filas y columnas, demostrando comprensión de los conceptos de diseño responsivo y su aplicación práctica. (1 punto) ⚠️ Hace uso de Flexbox en todo el documento, eso va mejorar la UX, sobre todo en dispositivos moviles. Podes ver como se vería tu página en un celular desde el inspector de chrome o el navegador que utilices

**GitHub (3 puntos):**
- Realización de commits necesarios sobre la rama de desarrollo utilizando Git. (1 punto) ✔️
- Creación de una rama "feature/segunda-entrega" a partir de la rama "develop" utilizando Git. (1 punto) ✔️
- Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "feature/primera-entrega" con "develop" en GitHub. (1 punto) ✔️

**Nota:** 9 (Nueve)

2024-10-01 20:07 UTC, Lucaaaa05 commented
@MVelasquez98 Profe fijese lo de las media querys, creeria que ahora tiene un diseño más optimo, lo que todavia no puedo solucionar son los conflictos.

2024-10-01 20:16 UTC, MVelasquez98 commented
Desde GithubPages, no se visualizan aún los cambios. Y tampoco cargan las imagenes, de todas formas puede tardar un rato en impactar en el servidor los cambios:
<img width="682" alt="image" src="https://github.com/user-attachments/assets/e19d3342-dd68-4b72-9ab3-dbe896a71904">
Lo que si tenes que revisar es que tenes conflictos de merge si intentas hacer rebase and merge. Aunque te de approve no te va dejar hacer merge, por los [conflictos](https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) que hay:
<img width="878" alt="image" src="https://github.com/user-attachments/assets/462228f7-068d-4b9d-a73e-0fa64212ea3e">
Podes hacer lo siguiente en tu local:

- Te moves a origin/develop
- Haces git pull
- Volves a la rama feature/segunda-entrega
- Haces desde vscode ... -> Rama -> Fusionar la rama mediante "rebase"

![image](https://github.com/user-attachments/assets/ac60e795-fece-42ae-9c91-20672e16630d)

- Escoges origin/develop del listado.
- [Resolves los conflictos](https://www.jorgeacortes.com/2019/01/resolver-conflictos-en-git-con-visual-studio-code/)que esten en los archivos marcados con advertencia ⚠️
- Asegurate de no pisar tus cambios
- Hace git add .
- Le das "Continuar" (el boton azul)
- Haces git push -f

Algunos videos que te pueden servir:
[Como Solucionar un Merge Conflict (Conflicto de Merge) En VSCode](https://youtu.be/uDDNwwxoaZY?si=eGG_ZhIXRfYpEmnn)
[Cómo resolver conflictos de versiones con VS Code](https://youtu.be/g7bbxEt09PI?si=bi26br5lpoyPY3-w)

2024-10-01 21:13 UTC, Lucaaaa05 commented
@MVelasquez98 seguí como usted me dijo profe y me sigue tirando lo de los conflictos

2024-10-02 15:15 UTC, MVelasquez98 commented
¿Hiciste push de los conflictos corregidos?¿Cuales eran los conflictos?¿Como los corregiste?

2024-10-02 16:41 UTC, Lucaaaa05 commented
> ¿Hiciste push de los conflictos corregidos?¿Cuales eran los conflictos?¿Como los corregiste?

Sisi creo que me falto forzar el push, eran conflictos sobre todo del css, dependiendo, habia algunas cosas que puse de más asi que en algunas aceptaba el incoming y en otras el current hasta que no pise las correciones

2024-10-02 17:05 UTC, MVelasquez98 approved these changes
LGTM
Te doy approve para que continues con el parcial ahora que ya resolviste los conflictos de merge. Pero aún no veo los cambios de diseño responsivo en la página y las imágenes siguen si cargar. Si se trata de un error compartime una captura de como lo visualizas vos. Si es algo a resolver, subilo en los cambios del parcial.
![image](https://github.com/user-attachments/assets/ab688344-0662-48d2-b490-12fcc63e5902)

2024-10-02 18:10 UTC, merged