Release/ primer parcial
Lucaaaa05/Programacion-Web-LucaE pull request #3
Opened 2024-10-02 20:01 UTC by Lucaaaa05

agregé un carrusel justo terminando el header, y en el footer agregé un iframe con un mapa

2024-10-04 18:13 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

**Incorporación de Componentes Avanzados de HTML (1 punto):**

- ⚠️ Agregar al menos un componente avanzado de HTML a la página, como un iframe de un video de YouTube o un mapa de Google Maps. (1 punto). El video incrustado no se visualiza. 

**Implementación de Bootstrap para Diseño Responsivo (5 puntos):**

- ✅ Instalar la biblioteca Bootstrap en el proyecto. (1 punto)
-  ⚠️ Utilizar el sistema de columnas de Bootstrap para hacer que el sitio sea más responsivo en dispositivos móviles. (3 puntos). Podría aprovecharse mejor el [sistema de columnas en Bootstrap](https://getbootstrap.esdocu.com/docs/5.1/layout/columns/) o [grilla](https://getbootstrap.com/docs/4.0/layout/grid/) para mejorar el [Diseño UI](https://perio.unlp.edu.ar/catedras/comyddhhlic/wp-content/uploads/sites/125/2023/02/Diseno-UX-UI.pdf), más que nada en dispositivos moviles. 
- ✅Incluir al menos un componente avanzado de Bootstrap, como un carrusel, una barra de navegación o un modal. (1 punto)

**Gestión del Proyecto con GitHub (4 puntos):**

- ✅ Realización de commits necesarios sobre la rama de desarrollo utilizando Git. (1 punto)
- ⚠️ Creación de una rama "release/primer-parcial" a partir de la rama "develop" utilizando Git. (1 punto) Vas a tener que resolver los [conflictos de merge](https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line) para la próxima entrega.
-  ✅ Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "feature/segunda-entrega" con "develop" en GitHub. (1 punto)
-  ✅ Proporcionar la URL de la pull request y la URL generada por GitHub Pages para la rama "release/primer-parcial" como parte de la entrega. (1 punto)

**Nota:** 7 (Siete)

2024-10-18 18:49 UTC, Lucaaaa05 commented
@MVelasquez98 Buenas profe, ahora el mapa se ve bien en dispositivos moviles, agregué nuevas imagenes para el carrusel y resolví los conflictos que habían.
Saludos

2024-10-20 17:29 UTC, MVelasquez98 approved these changes
LGTM
Ojo con el tamaño de las imagenes nuevas en el carrousel que pueden estar desbordando, te doy approve y podes resolver esto durante la tercer entrega:
![image](https://github.com/user-attachments/assets/156df038-cadb-42a5-b407-055d4513d092)

2024-10-20 17:29 UTC, MVelasquez98 commented on index.html
> +                <iframe
Cuidado con el desborde que esta generando el iframe en dispositivos moviles.
![image](https://github.com/user-attachments/assets/4226cb00-41d9-476c-9bbc-2b66062710d2)
Bootstrap te facilita los errores que se puedn generar con los [embed](https://getbootstrap.com/docs/4.0/utilities/embed/) de forma responsiva.

2024-10-20 19:34 UTC, merged