scripst y mejoras
Lucaaaa05/Programacion-Web-LucaE pull request #5
Opened 2024-10-22 00:52 UTC by Lucaaaa05

agregé 2 clases "Producto" y "InventarioProducto" , cada una con su respectivo script.
Funciones: agregar producto , buscar producto/s, mostrar en consola todos los productos agregados, validar el formulario de mensaje.
mejore un poco el carusel, haciendolo mas responsive.

2024-10-24 17:18 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

- **Algoritmos (1 punto)**
✅ 1 punto: Uso correcto y eficiente de algoritmos condicionales y ciclos.

- **Funciones (1 punto)**
⚠️ 0.5 puntos: Funciones con nombres claros, estructura correcta y resultados no del todo correctos. Hay errores en compilación.

- **Funcionalidad (1 punto)**
⚠️ 0.5 puntos Flujo de trabajo incompleto o funcionalidad inapropiada al contexto. La función de buscar productos no esta trayendo resultados correctos, la validación del formulario no imprime las respuesta de forma correcta.

- **Interactividad (1 punto)**
⚠️ 0.5 puntos: Interactividad insuficiente o salidas incoherentes. No me queda del todo claro como usarias la funcionalidad a futuro de agregarProductos en la página, no esta pensada una funcionalidad admin. Pensa que estas funcionalidades en la prróxima entrega van a ir adaptandose a los elementos html del sitio.

- **Escalabilidad (1 punto)**
⚠️ 0.5 puntos: Falta de funciones con parámetros. Una funcion que use algun parametro seria `function myFuncion(parametro)`

- **Legibilidad (1 punto)**
- ✅ 1 punto: Nombres significativos, código legible y bien estructurado.

**GitHub (4 puntos):**
- ✅ 1 punto: Creación de una rama "backport/primer-parcial" a partir de la rama "master" utilizando Git.
- ✅ 1 punto: Creación de una rama "feature/tercera-entrega" a partir de la rama "develop" utilizando Git.
- ❌ 0 puntos:: Correcta realización de la solicitud de revisión para fusionar la rama "backport/primer-parcial" con "develop" en GitHub, resolviendo los conflictos de merge (si fuese necesario). La pull request del backport lo hiciste al reves, hiciste merge de develop en tu rama "backport/primer-parcial", por eso hay 0 cambios. Esto te va generar un problema, porque es significa que los cambios del parcial no estan actualmente en develop, desde donde partiste para hacer esta entrega. Vas a tener que repetir el backport para no perder el control de ramas en git. 
- ✅ 1 punto: Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "release/primer-parcial" con "master" en GitHub,  resolviendo los conflictos de merge (si fuese necesario).

**Nota**: 7(Siete)

2024-10-24 17:18 UTC, MVelasquez98 commented on script.js
> +alert(`Se llama: ${datosFormulario.nombre} ${datosFormulario.apellido}, su mensaje es: ${datosFormulario.mensaje}`);
¿Donde esta la variable **datosFormulario** definida? Esto genera error:
![image](https://github.com/user-attachments/assets/8046ae1c-cf65-492d-bade-25fd4980ae6f)

2024-10-24 17:18 UTC, MVelasquez98 commented on script.js
> +    const validEmail = /^\w+([.-_+]?\w+)*@\w+([.-]?\w+)*(\.\w{2,10})+$/; // https://www.coderbox.net/blog/validar-email-usando-javascript-y-expresiones-regulares/
El comentario "`// https://www.coderbox.net/blog/validar-email-usando-javascript-y-expresiones-regulares/`" es innecesario

2024-10-24 17:18 UTC, MVelasquez98 commented on InventarioProducto.js
> +                producto.nombreProducto.includes(barraBusqueda) // busca dentro del array
Algo no esta funcionando bien en tu filtro de busqueda, revisar:
![image](https://github.com/user-attachments/assets/5e82381c-79fe-4057-83cc-96d472564bb5)

2024-10-24 17:23 UTC, MVelasquez98 commented
Esta pull request esta al reves, no tiene sentido si sumas +0 cambios, justamente la idea es sumar los cambios del parcial a develop:
![image](https://github.com/user-attachments/assets/180a8129-0a81-44aa-9ff6-2b2fa943abc1)
Corregir para que los cambios del parcial no se pierdan:
![image](https://github.com/user-attachments/assets/3908be1b-ff00-4ed5-afc2-cdbb720ffd0a)

2024-11-10 22:50 UTC, Lucaaaa05 commented
@MVelasquez98 
Buenas profe, no deberian haber problemas en la compilación.
-Defini la funcion de "datosFormularios" como una constante a lo ultimo, no deberia dar error.
-Eliminé el comentario innecesario.
-El filtro de busqueda funciona correctamente.

Ahora lo del método "agregarProducto", para que tenga sentido en mi trabajo, debo crear una funcionalidad en base "admin"? Porque sino de que otra forma se podrian agregar productos sin tener que modificar todo el codigo HTML o CSS?

Y por ultimo lo del backport, vi el comentario que me hizo en el campus, di vuelta y me sigue diciendo que no hay cambios, debe ser porque hice un pull para corregir los conflictos, actualizando develop.

Saludos

2024-11-11 13:56 UTC, MVelasquez98 requested changes
Ni bien hace load la página, hay este error en consola:
<img width="724" alt="image" src="https://github.com/user-attachments/assets/1e422991-c4e8-4ea0-80ab-eaa53295755c">
Que es en esta linea:
<img width="695" alt="image" src="https://github.com/user-attachments/assets/4a4765b9-2d2e-4ba5-879f-16e52d1b30a1">

2024-11-11 14:05 UTC, MVelasquez98 commented
Sigue faltando esto:
Escalabilidad (1 punto)
⚠️ 0.5 puntos: Falta de funciones con parámetros. Una funcion que use algun parametro seria function `myFuncion(parametro)`

Respecto al backport mucho cuidado, porque si no hiciste asi la atualización de develop, significa que hiciste directamente push de esos cambios en develop sin una pull request. 

Con la función `agregarProducto`, recorda que en este proyecto cuatrimestral estamos construyendo un [MVP](https://pmbc.es/que-es-el-producto-minimo-viable-mvp/) del proyecto, por lo que construir una funcion admin seria costoso respecto a tiempo. Los productos los podes almacenar estaticamente en una constante en el código por el momento, para el segundo parcial, vamos a ver una forma ordenada de hacerlo con JSON.

2024-11-11 14:51 UTC, Lucaaaa05 commented
@MVelasquez98 
Ahora creé un prompt que se llama "input" el cual detecta si el producto es "null" y cancela la operación, despues si se agrega un producto lo pasa todo a mayusculas con la linea "barraBusqueda = input.toUpperCase();" y seguidamente continua con la ejecucción normal.

Además agregué una función para mensajes personalizados dentro del programa, un caso de uso por ejemplo, puede ser que notifique al usuario de que agregó un producto a el carrito, y con la misma función que le indique que lo agregó a favoritos.

Con el tema backport, no hay ninguna manera de solucionarlo, o por ahora lo dejo así y lo realizo nuevamente para el segundo parcial?

2024-11-11 21:53 UTC, MVelasquez98 approved these changes
LGTM

Lo del backport por ahora dejalo así, pero tenelo en cuenta para el segundo parcial, que va volver a repetirse el proceso.

2024-11-14 15:24 UTC, merged