Funcionalidades nuevas
Lucaaaa05/Programacion-Web-LucaE pull request #8
Opened 2024-11-19 17:26 UTC by Lucaaaa05

realizé los cambios necesarios para la 4° entrega, ademas de cambiar algunas cosas del archivo index y styles

2024-11-21 18:24 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

- **Funcionalidad (2 puntos)**
⚠️ 0.5 puntos: Simula uno o más flujos de trabajo en términos de entrada, proceso y salida. Falta una salida final al usuario al finalizar la compra.
✅ 1 punto: La funcionalidad es apropiada al contexto del simulador y carece de errores de cómputo durante el procesamiento.

- **Interactividad (2 puntos)**
✅ 1 punto: Captura entradas ingresadas por el usuario mediante eventos.
✅ 1 punto: Efectúa una o más salidas por HTML modificando el DOM, con control de ingreso de entradas y salidas coherentes en relación a los datos ingresados.

- **Escalabilidad (2 puntos)**
✅ 0.5 puntos: Declara funciones con parámetros para definir instrucciones con una tarea específica.
✅ 0.5 puntos: Emplea arrays para agrupar valores relacionados.
⚠️ 0.5 puntos: Define objetos con propiedades y métodos relevantes al contexto. Pensar en utilizar una clase Carrito.
✅ 0.5 puntos: Establece un criterio homogéneo para la detección de eventos y almacena en storage datos relevantes generados durante la simulación.

- **Integridad (1 punto)**
✅ 0.5 puntos: Define el código JavaScript en un archivo .js, referenciándolo correctamente desde el HTML.
✅ 0.5 puntos: Evita métodos prompt() y alert() para evitar interrupciones durante el procesamiento y actualización del DOM, y emplea adecuadamente la información estática del proyecto.

Legibilidad (1 punto)
✅ 0.5 puntos: Los nombres de variables, funciones y objetos son significativos para el contexto.
⚠️ 0.5 puntos: Las instrucciones se escriben de forma legible y se emplean comentarios oportunos, manteniendo el código fuente ordenado en términos de declaración y secuencia. En algún punto el código hace demasiadas cosas, considero que con la clase `Carrito.js` se va solucionar.

- **GitHub (2 puntos):**

✅ 0.5 puntos: Realización de commits necesarios sobre la rama de desarrollo utilizando Git.
❌ 0 puntos: Creación de una rama "feature/cuarta-entrega" a partir de la rama "develop" utilizando Git. Cuidado que la rama marca este aviso `This branch is [7 commits ahead of](https://github.com/Lucaaaa05/Programacion-Web-LucaE/compare/master...feature/cuarta-entrega) master.` No queda nada más que verificar la proxima desde donde se parte el origen de la rama para crear otra.
✅ 1 punto: Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "feature/tercera-entrega" con "develop" en GitHub.

2024-11-21 18:24 UTC, MVelasquez98 commented on script.js
> +function guardarCarrito() {
Usar una clase para el carrito: Implementa una clase para encapsular la lógica del carrito. Esto mejora la reutilización y la claridad. Por ejemplo:

```
class Carrito {
    constructor() {
        this.productos = JSON.parse(localStorage.getItem("carrito")) || [];
    }

    guardar() {
        localStorage.setItem("carrito", JSON.stringify(this.productos));
    }

    agregar(nombre, precio) {
        if (!esProductoValido(nombre, precio)) return;
        // Lógica de agregar...
    }

    // Otras funciones...
}

```

2024-11-21 18:24 UTC, MVelasquez98 commented on script.js
> +    carrito.style.display = carrito.style.display === "none" ? "block" : "none";
Estilos dinámicos: Usa clases CSS para mostrar/ocultar el carrito en lugar de manipular directamente style.display. Esto mejora la mantenibilidad, por ejemplo:
`carrito.classList.toggle("visible");`

2024-11-21 18:24 UTC, MVelasquez98 commented on script.js
> +function agregarAlCarrito(nombreProducto, precioProducto) {
Implementa notificaciones visuales o alertas al usuario cuando se realizan acciones, como agregar un producto al carrito.

2024-11-21 18:24 UTC, MVelasquez98 commented on script.js
> +            if (!producto.nombre || isNaN(producto.precio) || isNaN(producto.cantidad)) {
Podrías centralizar las validaciones para evitar duplicación. Por ejemplo, crea una función validarProducto para verificar que el nombre y el precio del producto sean válidos. Luego, úsala en _agregarAlCarrito_ y _inicializarBotones_.
```
function validarProducto(nombreProducto, precioProducto) {
    return nombreProducto && !isNaN(precioProducto);
}
```

2024-11-21 18:24 UTC, MVelasquez98 commented on script.js
> +            const precioProducto = parseFloat(boton.dataset.precio);
Este es opcional respecto a Formato de números: Usa Intl.NumberFormat para formatear precios según la región:
```
const formateador = new Intl.NumberFormat("es-MX", {
    style: "currency",
    currency: "MXN",
});
console.log(formateador.format(1234.56)); // $1,234.56

```

2024-11-21 18:24 UTC, MVelasquez98 commented on index.html
> +        <button class="checkout-button">Finalizar Compra</button>
Estaría bueno para cerrar el circuito del simulador que al presionar este botón se imprima los datos de la compra en un [modal](https://getbootstrap.com/docs/4.0/components/modal/) quizas. Como ¡Compra existosa! con el detalle de la compra o similar.
```
// Evento para abrir el modal y mostrar el resumen
btnFinalizarCompra.addEventListener("click", () => {
// Función para renderizar los elementos del carrito en el modal
    mostrarResumenCompra();
    const modal = new bootstrap.Modal(document.getElementById("modalCompra"));
    modal.show();
});
```

2024-11-26 15:39 UTC, Lucaaaa05 commented
@MVelasquez98 Buenas profe como está, hice las correciones que me pidió:
- Creé una clase Carrito para almacenar los métodos necesarios y liberar el archivo "script.js"
- Mejoré los estilos dinamicos
- Creé un nuevo método para verificar los productos
- Por ultimo agregé un Modal cuando se finaliza la compra

Saludos.

2024-11-26 16:51 UTC, MVelasquez98 commented
Ojo que a nivel visual se te desacomodo el footer:
![image](https://github.com/user-attachments/assets/6264b6e0-c4d7-411c-b1a6-2829d5bae727)

2024-11-26 16:51 UTC, MVelasquez98 commented
Revisar comentarios

2024-11-26 19:47 UTC, Lucaaaa05 commented
@MVelasquez98 profe ahi agregué las notificaciones cuando se realizan eventos.


> Ojo que a nivel visual se te desacomodo el footer: ![image](https://private-user-images.githubusercontent.com/43156596/390063696-6264b6e0-c4d7-411c-b1a6-2829d5bae727.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDc1MDAsIm5iZiI6MTczMjY0NzIwMCwicGF0aCI6Ii80MzE1NjU5Ni8zOTAwNjM2OTYtNjI2NGI2ZTAtYzRkNy00MTFjLWIxYTYtMjgyOWQ1YmFlNzI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDE4NTMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNGUwYmMyM2I0YmZiYzYyODQxMGE1OGQxOTIyZWEzNWRjOTE0NmEwYzliNGRmZGRjNWFjZTQwZDg3MTAzNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.96liOuhgfngiIIOntvhFQ2iahPDtVX8cUyZ1LJXRgiA)

Estoy intentando arreglarlo pero no puedo, ahora qudó peor, alguna idea de cual es el problema??

2024-11-26 19:57 UTC, MVelasquez98 commented
No me parece tan importante ahora, corregilo para el parcial. Concentrate en corregir el resto de comentarios en el codigo respecto al uso de clases en .js, eso me interesa más

2024-11-26 20:45 UTC, Lucaaaa05 commented
@MVelasquez98 
- Usar una clase para el carrito: Implementa una clase para encapsular la lógica del carrito. Esto mejora la reutilización y la claridad.
Hecho, se crearon 2 nuevas clases para, "Carrito.js" y "Notificaciones.js" hacer que el codigo sea un poco mas legible, liberando el archivo principal "script.js".

- Estilos dinámicos: Usa clases CSS para mostrar/ocultar el carrito en lugar de manipular directamente style.display. Esto mejora la mantenibilidad.
Hecho:
```
document.getElementById("cart").addEventListener("click", () => {
    const carrito = document.getElementById("carrito");
    carrito.classList.toggle("visible");
});
```
- Implementa notificaciones visuales o alertas al usuario cuando se realizan acciones, como agregar un producto al carrito.
Hecho:
![image](https://github.com/user-attachments/assets/3b0061b1-ae07-4c17-a84b-5afc465c602d)
![image](https://github.com/user-attachments/assets/9042644a-c438-403a-829a-bdb9d93093b3)
![image](https://github.com/user-attachments/assets/9e1123ef-eb2c-42da-9f29-170479271ee6)
![image](https://github.com/user-attachments/assets/882ffb9b-0764-4413-89ba-ed61f26471b0)

- Podrías centralizar las validaciones para evitar duplicación. Por ejemplo, crea una función validarProducto para verificar que el nombre y el precio del producto sean válidos. Luego, úsala en agregarAlCarrito y inicializarBotones.
Hecho: 
```
validarProducto(nombreProducto, precioProducto) {
    if (!nombreProducto || typeof nombreProducto !== "string" || nombreProducto.trim() === "") {
        console.error("Nombre de producto inválido:", nombreProducto);
        return false;
    }
    if (isNaN(precioProducto) || precioProducto <= 0) {
        console.error("Precio de producto inválido:", precioProducto);
        return false;
    }
    return true;
}
```

- Este es opcional respecto a Formato de números: Usa Intl.NumberFormat para formatear precios según la región.
Hecho:
![image](https://github.com/user-attachments/assets/d49bdd9b-12f2-43cc-8b24-7a814dee8376)

- Estaría bueno para cerrar el circuito del simulador que al presionar este botón se imprima los datos de la compra en un [modal](https://getbootstrap.com/docs/4.0/components/modal/) quizas. Como ¡Compra existosa! con el detalle de la compra o similar.
Hecho:
![image](https://github.com/user-attachments/assets/507323ce-4ddb-49ea-9b76-4676a4698bff)

- Ojo que a nivel visual se te desacomodo el footer.
En proceso...

2024-11-26 23:42 UTC, MVelasquez98 approved these changes
LGTM

2024-11-26 23:42 UTC, MVelasquez98 commented on Carrito.js
> +        this.productos.push({ nombre: nombreProducto, precio: Number(precioProducto), cantidad: 1 });
En este punto tenes que usar la clase producto, sino es un objeto simpl. Por ejemplo:
`this.productos.push(new Producto(nombreProducto, Number(precioProducto), 1));
`

2024-11-26 23:42 UTC, MVelasquez98 commented on Carrito.js
> +            this.agregarAlCarrito(nombreProducto, precioProducto);
¿Es necesario pasar por separado esto? ¿No podes hacer uso de la clase producto? 
`new Producto(nombreProducto, precioProducto)`
Una vez que pasas la instancia y la recibis así, pode acceder a sus propiedades

2024-11-26 23:42 UTC, MVelasquez98 commented on Carrito.js
> +agregarAlCarrito(nombreProducto, precioProducto) {
¿No podría recibir como parametro la instancia de producto? Y despues utilizar internamente sus propiedades

2024-11-26 23:42 UTC, MVelasquez98 commented on Carrito.js
> +validarProducto(nombreProducto, precioProducto) {
¿No podría recibir como parametro la instancia de producto? Y despues utilizar internamente sus propiedades

2024-11-26 23:42 UTC, MVelasquez98 commented on Carrito.js
> + eliminarDelCarrito(nombreProducto) {
¿No podría recibir como parametro la instancia de producto? Y despues utilizar internamente sus propiedades

2024-11-26 23:42 UTC, MVelasquez98 commented on Carrito.js
> + incrementarCantidad(nombreProducto) {
¿No podría recibir como parametro la instancia de producto? Y despues utilizar internamente sus propiedades

2024-11-26 23:42 UTC, MVelasquez98 commented on Carrito.js
> +        producto.cantidad += 1;
Este seria un metodo de la clase Producto.js, en este punto solo llamo a 
`producto.inCrementarCantidad()`

2024-11-26 23:42 UTC, MVelasquez98 commented on Carrito.js
> +        producto.cantidad -= 1;
Este seria un metodo de la clase Producto.js, en este punto solo llamo a
`producto.decrementarCantidad()`

2024-11-26 23:42 UTC, MVelasquez98 commented on Carrito.js
> +import InventarioProducto from "./InventarioProducto.js";
Esta clase ya no la estas usando, eliminar el import, y considerar eliminar el archivo InventarioProducto.js si ya no lo usas

2024-11-26 23:42 UTC, MVelasquez98 commented on Carrito.js
> +import Producto from "./Producto.js";
Estas importando la Clase Producto, pero no la usas nunca

2024-11-27 00:14 UTC, merged